
INSERT INTO nhia_mdcs (`mdcs_id`, `code`, `mdc`, `age_id`, `service_type_id`, `gender_id`, `is_mdc`, `is_capitation`, `specialty_code`) VALUES
	('1', 'ASUR', 'ADULT SURGERY', '2', '3', '1', '1', 'No', 'ASUR'),
	('2', 'DENT', 'DENTAL AND MAXILLOFACIAL SURGERY', '3', '3', '1', '1', 'No', 'DENT'),
	('3', 'ENTH', 'EAR, NOSE AND THROAT SURGERY', '3', '3', '1', '1', 'No', 'ENTH'),
	('4', 'INVE', 'INVESTIGATIONS', '3', '4', '1', '1', 'No', 'INVE'),
	('5', 'MEDI', 'MEDICAL', '2', '2', '1', '1', 'No', 'MEDI'),
	('6', 'OBGY', 'OBSTETRICS AND GYNAECOLOGY', '2', '3', '1', '1', 'No', 'OBGY'),
	('7', 'OPDC', 'OPD', '3', '5', '1', '1', 'No', 'OPDC'),
	('8', 'OPHT', 'OPHTHALMOLOGY', '3', '3', '1', '1', 'No', 'OPHT'),
	('9', 'ORTH', 'ORTHOPAEDICS', '3', '3', '1', '1', 'No', 'ORTH'),
	('10', 'PAED', 'PAEDIATRICS', '1', '2', '1', '1', 'No', 'PAED'),
	('11', 'PSUR', 'PAEDIATRIC SURGERY', '1', '3', '1', '1', 'No', 'PSUR'),
	('12', 'RSUR', 'RECONSTRUCTIVE SURGERY', '3', '3', '1', '1', 'No', 'RSUR'),
	('13', 'ZOOM', 'CROSS-MDC', '3', '3', '1', '1', 'No', 'ZOOM'),
	('14', 'OPDC01', 'SURGERY (ORTHOPAEDIC)', '3', '3', '1', '0', 'No', 'ORTH'),
	('15', 'OPDC02', 'ANTENATAL/POSTNATAL', '2', '5', '3', '0', 'No', 'OPDC'),
	('16', 'OPDC03', 'DENTAL OPD', '3', '5', '3', '0', 'No', 'DENT'),
	('17', 'OPDC04', 'ENT OPD', '3', '5', '3', '0', 'No', 'ENTH'),
	('18', 'OPDC05', 'EYE OPD', '3', '5', '3', '0', 'No', 'OPHT'),
	('19', 'OPDC06', 'GENERAL OPD', '3', '5', '3', '0', 'No', 'OPDC'),
	('20', 'OPDC07', 'MEDICAL OPD', '3', '5', '3', '0', 'No', 'MEDI'),
	('21', 'OPDC08', 'GYNAECOLOGY OPD', '3', '5', '3', '0', 'No', 'OBGY'),
	('22', 'OPDC09', 'PAEDIATRIC SURGERY OPD', '1', '5', '3', '0', 'No', 'PSUR'),
	('23', 'OPDC10', 'PAEDIATRICS OPD', '1', '5', '3', '0', 'No', 'PAED'),
	('24', 'OPDC11', 'UNBUNDLED CONSULTATION', '3', '5', '3', '0', 'No', 'OPDC'),
	('29', 'OPDC13', 'PHYSIOTHERAPY', '3', '5', '3', '0', 'No', 'OPDC'),
	('30', 'ZOOM04', 'CHANGE OF CATHETER', '3', '5', '1', '0', 'No', 'ZOOM'),
	('32', 'ZOOM05', 'CHANGE OF DRESSING', '3', '5', '1', '0', 'No', 'ZOOM'),
	('34', 'OPDC01', 'ORTHOPAEDIC SURGERY', '3', '5', '1', '0', 'No', 'ORTH'),
	('36', 'OPDC14', 'CAPITATION OPD', '3', '5', '1', '0', 'Yes', 'OPDC'),
	('40', 'OPDC12', 'SURGERY (GENERAL AND RECONSTRUCTIVE)- ADULT', '3', '5', '1', '0', 'No', 'RSUR'),
	('41', 'ZOOM01', 'Endoscopy (Rigid & Flexible)', '3', '10', '1', '0', 'No', 'ZOOM'),
	('42', 'ZOOM02', 'Detention for Observation and Treatment', '3', '10', '1', '0', 'No', 'ZOOM'),
	('43', 'ZOOM03', 'Inpatient transfer out/Referral', '3', '10', '1', '0', 'No', 'ZOOM'),
	('44', 'ZOOM06', 'Male Circumcision', '3', '10', '1', '0', 'No', 'ZOOM'),
	('45', 'ZOOM07', 'Dressing And Minor Suturing', '3', '10', '1', '0', 'No', 'ZOOM'),
	('46', 'ZOOM08', 'TUBAL LIGATION', '3', '10', '1', '0', 'No', 'ZOOM'),
	('47', 'ZOOM09', 'VASECTOMY', '3', '10', '1', '0', 'No', 'ZOOM'),
	('48', 'ZOOM10', 'INTRA UTERINE DEVICE(IUD)', '3', '10', '1', '0', 'No', 'ZOOM'),
	('49', 'ZOOM11', 'IMPLANT', '3', '10', '1', '0', 'No', 'ZOOM'),
	('50', 'ZOOM12', 'INJECTABLE(THREE MONTHS)', '3', '10', '1', '0', 'No', 'ZOOM'),
	('51', 'ZOOM13', 'INJECTABLE(ONE MONTH)', '3', '10', '1', '0', 'No', 'ZOOM');