INSERT INTO `service_types` (`service_type_id`, `service_type`) VALUES 
	(1,'DRUG'),
	(2,'DIAGNOSIS'),
	(3,'SURGERY'),
	(4,'INVESTIGATION'),
	(5,'CONSULTATION'),
	(6,'ACCOMODATION'),
	(7,'MEAL'),
	(8,'TRANSPORTATION'),
	(9,'OPD'),
	(10,'OTHER'),
	(11,'LABORATORY'),
	(12,'XRAY'),
	(13,'ECG'),
	(14,'ULTRASOUNDSCAN'),
	(15,'LAUNDARY'),
	(17,'DETENTION'),
	(16,'REFFERALS');
